### ISSUE TITLE
crush on 1.18.2 at the start of the game launch

### ISSUE THREAD

**Issue by AlanBanan23** [InfinityStudio/GokiStats#100]
-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
-- MOD gokistats --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/common/Tags$IOptionalNamedTag
		at net.infstudio.goki.api.stat.Stats.<clinit>(Stats.java:15) ~[GokiStats-1.18.1-1.4.0.jar%2365!/:1.4.0] {re:classloading}
		at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
		at java.lang.Class.forName(Class.java:375) ~[?:?] {re:mixin}
		at net.infstudio.goki.GokiStats.construct(GokiStats.java:43) ~[GokiStats-1.18.1-1.4.0.jar%2365!/:1.4.0] {re:classloading}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.76.jar%2375!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.76.jar%2374!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/Alan/AppData/Roaming/.minecraft/mods/GokiStats-1.18.1-1.4.0.jar
	Failure message: Goki Stats (gokistats) encountered an error during the common_setup event phase
		java.lang.NoClassDefFoundError: net/minecraftforge/common/Tags$IOptionalNamedTag
	Mod Version: 1.4.0
	Mod Issue URL: https://github.com/InfinityStudio/GokiStats/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.common.Tags$IOptionalNamedTag
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at net.infstudio.goki.api.stat.Stats.<clinit>(Stats.java:15) ~[GokiStats-1.18.1-1.4.0.jar%2365!/:1.4.0] {re:classloading}
	at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.forName(Class.java:375) ~[?:?] {re:mixin}
	at net.infstudio.goki.GokiStats.construct(GokiStats.java:43) ~[GokiStats-1.18.1-1.4.0.jar%2365!/:1.4.0] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.76.jar%2375!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.76.jar%2374!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by Forsoyeur** [comment]
does anyone know how to solve this problem?

**Comment by LasmGratel** [comment]
GokiStats targeted a much older 1.18 Forge version, I will have that updated
