### ISSUE TITLE
1.2.7版本在服务器中使用会导致崩溃错误

### ISSUE THREAD

**Issue by YukiCoco** [InfinityStudio/GokiStats#42]
错误是由于**闪避**技能导致的，在 CatServer 中使用，会导致服务器崩溃，在 Sponge 中使用，会导致无法储存玩家资料且玩家掉线。

Sponge 中的 Log：
```
[23:57:28] [Server thread/WARN] [net.minecraft.world.storage.SaveHandler]: Failed to save player data for Patients_LA
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1772) ~[vg.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75753_a(SaveHandler.java:184) [bfb.class:?]
	at net.minecraft.server.management.PlayerList.func_72391_b(PlayerList.java:348) [pl.class:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:391) [pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:853) [pa.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
	at net.minecraft.potion.PotionEffect.getCurativeItems(PotionEffect.java:264) ~[va.class:?]
	at net.minecraft.potion.PotionEffect.writeCurativeItems(PotionEffect.java:311) ~[va.class:?]
	at net.minecraft.potion.PotionEffect.func_82719_a(PotionEffect.java:206) ~[va.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70014_b(EntityLivingBase.java:535) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70014_b(EntityPlayer.java:935) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70014_b(EntityPlayerMP.java:246) ~[oq.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1743) ~[vg.class:?]
	... 11 more
```

**Comment by NanamiArihara** [comment]
不知道为何@ObjectHolder不能用了
