### ISSUE TITLE
[1.15] Server Crash log

### ISSUE THREAD

**Issue by Cixon** [InfinityStudio/GokiStats#56]
[14Aug2020 20:22:49.590] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Goki Stats (gokistats) has failed to load correctly
§7Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:200) ~[?:?]
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[14Aug2020 20:22:49.600] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: C:\Users\eli\Desktop\Server\OUR SERVER\.\crash-reports\crash-2020-08-14_20.22.49-server.txt
[14Aug2020 20:22:49.611] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[14Aug2020 20:22:49.611] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[14Aug2020 20:22:49.612] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Exception stopping the server
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
	at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:185) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1004) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:536) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:550) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:676) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by Cixon** [comment]
The client player entity dist is incorrect. This must be fixed.
